# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Chto.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from threading import Thread
from client import Client

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("ONE")
        MainWindow.resize(317, 394)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 10, 281, 311))
        self.textBrowser.setObjectName("textBrowser")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 340, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 348, 51, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(lambda: self.send_masange())
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        client2 = Client('Pasha', '', 50004)

        p1 = Thread(target=client2.get_message)
        # p2 = Thread(target=client2.send_message, args=('localhost', 50004))

        p1.start()
        # p2.start()
        # print(p1)

    def get_messange_in_sobesednic(self, data):
        Text_2 = self.textBrowser.toPlainText()
        text_3 = Text_2 + '\n' + 'Собеседник: ' + data
        self.textBrowser.setText(text_3)


    def send_masange(self):
        text = self.plainTextEdit.toPlainText()
        Client.send_message('localhost', 50003, text)
        self.plainTextEdit.setPlainText('')
        Text_2 = self.textBrowser.toPlainText()
        text_3 = Text_2 + '\n' + 'Вы: ' + text
        self.textBrowser.setText(text_3)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "SEND"))
def run_get_messange_in_sobesednic(data):
    get_messange_in_sobesednic(data)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
